Changed invoice date to datetime
InvoiceShelf/InvoiceShelf pull request #136
Opened 2024-08-09 07:21 UTC by troky

Added possibility to use time in invoices.

2024-08-09 07:29 UTC, mchev commented
Thank you for the work! In what scenario is it necessary to include the time on an invoice? If needed, this information is automatically populated in the 'created_at' field by default."

Also, I've changed the target branch to `develop` now.

2024-08-09 07:34 UTC, troky commented
> Thank you for the work! In what scenario is it necessary to include the time on an invoice? If needed, this information is automatically populated in the 'created_at' field by default."

In Croatia invoice date AND time are mandatory (at minutes resolution) so when creating new invoice user has possibility to enter exact invoice date and time in DateTime picker. Entering time is optional as per Invoice preferences.

2024-09-25 08:18 UTC, mchev approved these changes

2024-09-25 09:14 UTC, mchev commented on app/Http/Controllers/V1/Admin/General/TimeFormatsController.php
The namespace is now App\ instead of InvoiceShelf\

2024-09-25 10:23 UTC, troky reviewed
Fixed namespaces

2024-11-17 00:17 UTC, gdarko requested changes
Hey @troky,

This looks great and it's almost good for approval.  We still have one place to replace the old namespace.

Please check the above comments.

2024-11-17 00:17 UTC, gdarko commented on app/Http/Controllers/V1/Admin/General/TimeFormatsController.php
> +use InvoiceShelf\Http\Controllers\Controller;
We need to rename this namespace to `App`, otherwise it throws an error.

![image](https://github.com/user-attachments/assets/a7976800-457e-4cb5-a367-b259a08145a0)

2024-11-18 15:12 UTC, troky commented on app/Http/Controllers/V1/Admin/General/TimeFormatsController.php
> +use InvoiceShelf\Http\Controllers\Controller;
Namespace renamed.

2025-01-12 09:32 UTC, gdarko requested changes
Hey @troky,

There is a small issue with missing `,`.

Best Regards,
Darko

2025-01-12 09:32 UTC, gdarko commented on lang/en.json
> +      "invoice_use_time_description": "Enable this if you want to select exact invoice time."
Missing "," causes the JS build to fail.

2025-01-12 09:34 UTC, closed without merging

2025-01-12 12:40 UTC, gdarko commented
Hey @troky  - I merged this. Thanks! Great work.