refactor: Update file paths for stub files for module creation
InvoiceShelf/InvoiceShelf pull request #144
Opened 2024-08-22 11:40 UTC by Heddy147

The file paths were wrong.
InvoiceShelf has changed the paths to the source stub files.
Although the destination file paths does not match to the structure of original modules.

Cause of wrong source file paths the replacements were wrong too.

2024-08-23 17:06 UTC, azaricstefan commented
Does this PR fix the modules or?

2024-09-20 10:30 UTC, Heddy147 commented
This fix the command module making command.

2024-11-16 23:47 UTC, gdarko requested changes
This looks good to me.  We just need to address the route adjustment. 

Thanks @Heddy147

2024-11-16 23:47 UTC, gdarko commented on resources/scripts/admin/admin-router.js
> +    name: 'admin',
Can we remove this or address it in separate PR to keep things clean? @Heddy147

2025-01-12 09:39 UTC, merged

2025-01-12 09:40 UTC, gdarko commented
Since the user didn't responded back. I will correct it in a separate branch `module-paths`.