Fix `make:template` command
InvoiceShelf/InvoiceShelf pull request #146
Opened 2024-09-03 21:51 UTC by stevenrombauts

This PR fixes the `make:template` command by:

1. Correcting the path for the image
2. Running the `npm run build` step afterwards. Without this you'll get a Vite error alert if you try to open the invoice or estimate edit form

Based on my limited knowledge of the app, this works great for me. If this might need anything else, let me know!

2024-09-23 10:02 UTC, mchev commented on app/Console/Commands/CreateTemplateCommand.php
How about using `Symfony\Component\Process\Process` to run the `npm run build`command? It would make error handling and logging smoother and more robust.

2024-10-10 21:03 UTC, stevenrombauts commented on app/Console/Commands/CreateTemplateCommand.php
Great idea @mchev, I've made changes to use `symfony/process`. If the build command fails, it also cleans up by removing the copied files now.

2024-11-16 23:57 UTC, gdarko requested changes
This works great in dev where we have package.json and all the build related stuff. 

However the `npm run build` will fail on production builds or installs that use the packaged zip file downloaded from the website or under the Git repository releases called "InvoiceShelf.zip". 

Why do we need to re-build the project? Maybe we can rectify that in a different way, perhaps manually?

@stevenrombauts , @mchev

2024-11-17 17:05 UTC, rihards-simanovics commented
@gdarko it likely has to do with the fact that the image of the invoice/estimate has to be part of the manifest and if it's not there but referenced in the code it generates a type error or panics as it doesn't know where to find the image.

2025-01-12 15:14 UTC, gdarko commented
Closed in favor of #272

2025-01-12 15:15 UTC, closed without merging