refactor: Migrate from Sass to PostCSS and Tailwind, introduce Vitest…
InvoiceShelf/InvoiceShelf pull request #212
Opened 2024-11-11 16:43 UTC by loduis

… tests for BaseContentPlaceholders, BaseContentPlaceholdersBox and BaseContentPlaceholdersText.

![image](https://github.com/user-attachments/assets/c804cbab-3843-46f3-91be-c6e98832d887)

2024-11-15 23:07 UTC, gdarko reviewed
Hey @loduis,

 Excuse my ignorance, what are the benefits to this?
 
I will be testing this in more details and I am happy to merge this if all good. 
 
 Thanks.

2024-11-15 23:23 UTC, loduis commented
The approach is to move to native CSS wherever possible and avoid relying on Sass. Given the CSS standard, we can achieve this with postcss-preset-env if needed. https://preset-env.cssdb.org/.  You only need to know CSS to make this approach work.

Also, include a bit of [Vitest's browser feature](https://vitest.dev/guide/browser/) to view the component without needing to navigate through the app to find where it’s used. This is especially helpful if refactoring is needed.

2024-11-16 19:22 UTC, rihards-simanovics commented
> The approach is to move to native CSS wherever possible and avoid relying on Sass. Given the CSS standard, we can achieve this with postcss-preset-env if needed. https://preset-env.cssdb.org/. You only need to know CSS to make this approach work.

I wouldn't worry about sass going away any time soon, if anything, I use it in all my projects. The jump from CSS to SASS isn't huge and besides CSS itself is now beginning to support SASS features like nesting, with a very similar syntax I might add.

Changing from SASS to CSS for the sake of changing it doesn't make sense to me, and only makes it harder to maintain, I am pro adding extra tests for Vue and perhaps even tailwind but once I begin reworking the frontend I will be working with sass.

@loduis I would say discard the PostCSS changes and keep the rest. I am already reviewing the frontend for invoiceShelf and in the coming months will begin working on rebuilding it in React Native, so sass needs to stay.

2024-11-16 19:29 UTC, rihards-simanovics requested changes
All changes from SASS to CSS need to be reverted. As mentioned in my previous comment future development will be utilising SASS.

2025-06-11 13:29 UTC, gdarko commented
For now we don't need this. If we decide to migrate to PostCSS then we can definitely look back on this PR.

2025-06-11 13:29 UTC, closed without merging