Added stock to items to allow tracking of items
InvoiceShelf/InvoiceShelf pull request #246
Opened 2024-12-09 11:02 UTC by TalibY22

This pr aim to help the user keep track of his inventory opening stock is added to the items table this allows users to enter their current stock when creating a item.whenever a invoice is finalized the stock is automatically deducted in summary this feature will be usefull in keeping track of inventory.

2024-12-09 22:39 UTC, gdarko requested changes
Hey @TalibY22 

Can we add switch option in the company settings under the "Preferences" tab to turn on/off this feature? 

If the feature is turned off, no stock field will show in the items page and the logic for reducing the opening_stock will be disabled, also the column in the items table won't show.

Best Regards,
Darko

2024-12-10 09:18 UTC, mchev requested changes

2024-12-10 09:18 UTC, mchev commented on app/Http/Controllers/V1/Admin/Invoice/ChangeInvoiceStatusController.php
Illuminate\Support\Facades\DB is not used.
Also reducing stock based on item quantity should only be applied if the opening_stock_enabled === true

2024-12-10 09:18 UTC, mchev commented on database/migrations/2024_12_09_100344_add_opening_stock_to_items_table.php
Missing the down method. `$table->dropColumn('opening_stock');`
May be the `opening_stock` field should be 0 by default and possibly nullable ?

2024-12-10 09:18 UTC, mchev commented on resources/scripts/admin/views/items/Index.vue
Not sure why you removed imports and fetchItemUnits, searchUnits, removeMultipleItems

2024-12-10 09:18 UTC, mchev commented on resources/scripts/admin/views/settings/PreferencesSetting.vue
I'm wondering if boolean isn't a safer value than YES and NO

2024-12-13 07:01 UTC, TalibY22 commented on resources/scripts/admin/views/settings/PreferencesSetting.vue
sure lemme work on the changes

2024-12-17 06:45 UTC, TalibY22 commented on resources/scripts/admin/views/settings/PreferencesSetting.vue
changes have been added

2024-12-17 08:45 UTC, mchev commented
Thanks @TalibY22, looks good to me

2024-12-17 08:45 UTC, mchev approved these changes

2024-12-17 08:50 UTC, TalibY22 commented
> Hey @TalibY22
> 
> Can we add switch option in the company settings under the "Preferences" tab to turn on/off this feature?
> 
> If the feature is turned off, no stock field will show in the items page and the logic for reducing the opening_stock will be disabled, also the column in the items table won't show.
> 
> Best Regards, Darko

changes added @gdarko

2025-01-12 10:14 UTC, gdarko requested changes

2025-01-12 10:14 UTC, gdarko commented on app/Http/Controllers/V1/Admin/Settings/UpdateSettingsController.php
> +            \Log::info('Stock management setting updated:', ['manage_stock' => $manageStock]);
This is not needed.

2025-01-12 10:14 UTC, gdarko commented on database/migrations/2024_12_09_100344_add_opening_stock_to_items_table.php
> +            $table->integer('opening_stock')->nullable()->default(0);
Can we add this after the `price` column?

2025-01-12 10:14 UTC, gdarko commented on database/migrations/2024_12_09_100344_add_opening_stock_to_items_table.php
> +            //
Remove this.

2025-01-12 10:14 UTC, gdarko commented on resources/scripts/admin/views/settings/PreferencesSetting.vue
Hey @TalibY22 , @mchev 

Let's keep 'YES' and 'NO' for consistency sake. All of the other switchers are with YES/NO value.

2025-01-15 07:06 UTC, TalibY22 commented
Changes made

2025-01-15 09:46 UTC, TalibY22 commented
NO idea on how to go around the merge issue just reverted from boolean to yes and no

2025-01-15 10:08 UTC, rihards-simanovics commented
> NO idea on how to go around the merge issue just reverted from boolean to yes and no

Thanks @TalibY22, fantastic work! 🎉

I've requested Darko to review he should get back to you soon.

2026-04-21 03:35 UTC, StonedDawg commented
hi, I tried this feature, but it didn't deduct the quantity after creating a sales invoice and also the "initial quantity" keep reverting back to empty (not 0, but empty input box)

2026-06-12 09:25 UTC, gdarko commented
Closing for inactivity, this feature will be re-worked in the 3.x branch.

2026-06-12 09:25 UTC, closed without merging