Adding Flat Tax support with fixed amount
InvoiceShelf/InvoiceShelf pull request #253
Opened 2024-12-12 15:56 UTC by mchev

# Add Support for Fixed Amount (Flat) Tax Types

## Overview
This PR introduces the ability to add and manage fixed amount (flat) taxes in the system, expanding our tax calculation capabilities beyond percentage-based taxes.

## Key Changes
- Added support for 'fixed' calculation type in tax types
- Enhanced tax display to show either percentage or fixed amount based on calculation type
- Updated tax amount calculations to handle both percentage and fixed amount scenarios
- Modified tax type selector to display formatted fixed amounts in the local currency

## UI Changes
- Tax type dropdown now shows:
  - Percentage taxes as: "Tax Name (10%)"
  - Fixed taxes as: "Tax Name ($10.00)"

## Technical Details
- Added `calculation_type` field support ('fixed' or 'percentage')
- Fixed amount values are stored in cents (integer) and displayed in decimal format
- Tax calculations now branch between:
  - Fixed: Uses the predefined fixed_amount
  - Percentage: Calculates based on item price * percentage

## Testing Instructions
1. Create a new tax type with fixed amount
2. Add the fixed tax to an item
3. Verify the tax amount is correctly applied regardless of item price
4. Test both fixed and percentage taxes on the same item
5. Verify tax calculations in invoices/estimates

## Screenshot
![Capture d’écran 2024-12-12 à 16 54 20](https://github.com/user-attachments/assets/4137f259-d2ca-4b72-b99f-9fcdb02fe11c)

## Related Issues
Closes #249

2024-12-13 07:07 UTC, rihards-simanovics commented
Thanks @mchev, will take a look at the Vue changes over the weekends. I'll leave the rest for Darko.

2025-01-12 12:05 UTC, gdarko reviewed
Hey @mchev 

This looks great. 

What do you think about simplifying the table UI a bit?

- Keep the calculation type column and join both percent and fixed amount into one called "amount". Add the necessary symbol (fixed: currency, percent: %) besides the value.?

Best Regards,
Darko

2025-01-13 08:12 UTC, mchev commented
> Hey @mchev
> 
> This looks great.
> 
> What do you think about simplifying the table UI a bit?
> 
>     * Keep the calculation type column and join both percent and fixed amount into one called "amount". Add the necessary symbol (fixed: currency, percent: %) besides the value.?
> 
> 
> Best Regards, Darko

Hi @gdarko, good idea. I just made the change.

2025-04-05 11:38 UTC, gdarko commented
Hi @mchev  - This looks fine, except it says 0% even if it is fixed when adding a tax to invoice.

I think it should be a quick one and then we can merge it.

![image](https://github.com/user-attachments/assets/00ba3f5a-67ac-493a-9e66-371ac3a787e1)

2025-04-05 11:38 UTC, gdarko requested changes
Hi @mchev  - This looks fine, except it says 0% even if it is fixed when adding a tax to invoice.

I think it should be a quick one and then we can merge it.

![image](https://github.com/user-attachments/assets/00ba3f5a-67ac-493a-9e66-371ac3a787e1)

2025-04-12 00:08 UTC, gdarko commented
> > Hi @mchev - This looks fine, except it says 0% even if it is fixed when adding a tax to invoice.
> > I think it should be a quick one and then we can merge it.
> > ![image](https://private-user-images.githubusercontent.com/5760249/430615834-00ba3f5a-67ac-493a-9e66-371ac3a787e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQwOTk3ODcsIm5iZiI6MTc0NDA5OTQ4NywicGF0aCI6Ii81NzYwMjQ5LzQzMDYxNTgzNC0wMGJhM2Y1YS02N2FjLTQ5M2EtOWU2Ni0zNzFhYzNhNzg3ZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MDhUMDgwNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVlNzNiNGU4N2I4ODYyYTBlNGY3OTE1ZDgzNDJjODVlN2U1MTAxZGJmZTkxOTY5MWIyOTZjMzg2YTk3NWM3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5RobDrU0Q9wnTqW4K7oA10TzJ3ujInFD6hvzet0oIiI)
> 
> That's strange, I just tested it locally and it works with currency. Did you run the migration before creating taxes?

Hi @mchev  - 

I believe the issue is in `resources/scripts/admin/components/estimate-invoice-common/SelectTaxPopup.vue` on line 113, the `{{ taxType.percent }} %` is hardcoded.

2025-05-02 09:52 UTC, mchev commented
Should be good now

2025-05-04 00:19 UTC, gdarko approved these changes
Great job @mchev

2025-05-04 00:24 UTC, merged