Complete dashboard translations
InvoiceShelf/InvoiceShelf pull request #69
Opened 2024-05-08 12:59 UTC by agencetwogether

Hello, 

Long time ago, I did a pull request on crater repo to fix many hardcoding strings, fix some bugs.
This PR has never merged... So I decide to transpose my work here.
Initial commit was : [https://github.com/crater-invoice/crater/pull/1020/files](https://github.com/crater-invoice/crater/pull/1020/files)

I think I'll do many commits, whereas a big .

So the first one is centralized to dashboard page.
Review my commit to see details.

Thanks

PS. : I'm a french developper, so I want to render completely InvoiceShelf fully translatable, without strings hardcoded.

Closes #91

2024-05-11 15:21 UTC, gdarko commented
Hey @agencetwogether - Thanks so much for this, I will review and get back/merge it asap.

2024-05-12 07:08 UTC, nielsdrost7 commented on config/app.php
Only trying to help:
When you put this to `fr` the locale for everyone is suddenly French.
So keep this one on `en`

2024-05-12 07:51 UTC, agencetwogether commented
I edited config to rollback to en locale

I set this to show you and reflect changes, principally with dates in dashboard. 
If I don’t change locale in config file, dates not translated. 
Do you know what is the way to translate dates when user change language in settings language in application without touch the locale directly ?

2024-05-12 13:56 UTC, gdarko requested changes
I think, `locale` setting should be as follows:

```
'locale' => env('APP_LOCALE', 'en'),
```

This way we can allow adjustments from the `.env` file.

2024-05-16 14:02 UTC, agencetwogether commented
Hello, I continued to translate the project. 

Notably :

- the customer portal uses the language defined in the company settings, 
- the installation wizard has a step at the beginning to choose the installation language, and ```APP_LOCALE``` is added directly at the end of installation to the ```.env``` file , so as to have the dates translated.
- status estimates, status invoices are translated
- and many others translations in files...

See my commit to see all stuff

[https://github.com/InvoiceShelf/InvoiceShelf/pull/69/commits/b85db8f4b7db5f355bf95fedbeaad8d749865d8a](https://github.com/InvoiceShelf/InvoiceShelf/pull/69/commits/b85db8f4b7db5f355bf95fedbeaad8d749865d8a)

Keep in mind I work with ```en.json``` and ```fr.json``` so for others languages, keys must have to added in respective file.

Thank you

2024-06-02 13:31 UTC, gdarko commented
Hey @agencetwogether  - Is this PR ready or you are planning to do more work? I am asking because i would like to review it.

2024-06-02 20:47 UTC, gdarko requested changes
@agencetwogether , @yagrasdemonde 

The PR looks wonderful and we are really close to merge it.

Please review the review comments i sent and if possible do those changes. 

One last thing: Can we add the language (step 0) to the top nav as well? 

Thanks for the wonderful work!

2024-06-02 20:47 UTC, gdarko commented on resources/scripts/admin/views/installation/Step3DatabaseConfig.vue
> +console.log('ollal')
Can we remove this? Thanks.

2024-06-02 20:47 UTC, gdarko commented on resources/views/emails/viewed/estimate.blade.php
> +{{ $data['user']['name'] }} @lang('mail_viewed_estimate')
Can we change this to accumulate the whole phrase? Something like this:

```
@lang('mail_viewed_estimate', ['name' => $data['user']['name']])
```

Note: I am not sure if @lang works with parameters, but in case it doesn't please use `__('string', [..parameters])`.

This way we are not hard-coding the name position. Some languages may have it in different position.

2024-06-02 20:47 UTC, gdarko commented on resources/views/emails/viewed/invoice.blade.php
> +{{ $data['user']['name'] }} @lang('mail_viewed_invoice')
Can we change this to accumulate the whole phrase? Something like this:

```
@lang('mail_viewed_invoice', ['name' => $data['user']['name']])
```

Note: I am not sure if @lang works with parameters, but in case it doesn't please use `__('string', [..parameters])`.

This way we are not hard-coding the name position. Some languages may have it in different position.

2024-06-03 11:56 UTC, agencetwogether commented
Hello @gdarko 

I fixed files to review. 
And now, installation top nav (wizard) is fixed accordingly with steps number

And yes, at this time my PR is ready.
If I find something new to translate or modify, I will make a new PR 😊

It's a real pleasure for me if you find this PR useful.

2024-06-03 12:06 UTC, gdarko commented
Hey @agencetwogether 

It just requires a pint (code style) by using vendor/bin/pint command and then we are good to go.

This is very useful PR by the way. Amazing work!

2024-06-05 10:05 UTC, gdarko approved these changes
Approved for merging

2024-06-05 10:07 UTC, merged