Fix custom fields
InvoiceShelf/InvoiceShelf pull request #78
Opened 2024-05-22 22:48 UTC by azaricstefan

I tested latest master branch, and it still has leftover model name Crater for custom fields.

Custom fields were broken due to leftover of Model name Crater.

Created migration to fix this.

This pr could fix [#50](https://github.com/InvoiceShelf/InvoiceShelf/issues/50).

cc: @tnga @gdarko

2024-05-22 23:16 UTC, azaricstefan commented
Added quick fix for this feature also https://docs.invoiceshelf.com/guide/custom-templates.html

This line is not required.

2024-06-02 09:20 UTC, Honigbrot commented
While this approach is totally valid and efficient, we could leverage Laravel's query builder to make the code more in line with Laravel's practices.

`  DB::table('custom_field_values')->update([
            'custom_field_valuable_type' => DB::raw("REPLACE(custom_field_valuable_type, 'Crater', 'InvoiceShelf')")
        ]);`

2024-06-02 20:55 UTC, gdarko commented
Thanks @Honigbrot for the suggestion. 

I am going to open a new issue #90 because we have multiple migrations that use raw syntax which is not very optimal.

2024-06-02 20:57 UTC, gdarko requested changes

2024-06-02 20:57 UTC, gdarko commented on database/migrations/2024_05_22_223547_replace_crater_custom_fields.php
> +        DB::update("UPDATE custom_field_values SET custom_field_valuable_type = REPLACE(custom_field_valuable_type, 'Crater', 'InvoiceShelf')");
Hey @azaricstefan - Go ahead and use the syntax as suggested by @Honigbrot. Once done this will be merged.

2024-06-02 20:57 UTC, gdarko commented on database/migrations/2024_05_22_223547_replace_crater_custom_fields.php
> +        DB::update("UPDATE custom_field_values SET custom_field_valuable_type = REPLACE(custom_field_valuable_type, 'InvoiceShelf', 'Crater')");
Hey @azaricstefan - Go ahead and use the syntax as suggested by @Honigbrot. Once done this will be merged.

2024-06-02 22:28 UTC, azaricstefan commented on database/migrations/2024_05_22_223547_replace_crater_custom_fields.php
> +        DB::update("UPDATE custom_field_values SET custom_field_valuable_type = REPLACE(custom_field_valuable_type, 'Crater', 'InvoiceShelf')");
Agreed, just pushed update as per @Honigbrot.

2024-06-03 12:14 UTC, gdarko approved these changes

2024-06-05 12:46 UTC, gdarko commented
Hey @azaricstefan  - Sorry to nag you again, looks like it still doesn't pass code style check. Can you please re-run pint? Thanks.

2024-06-05 12:47 UTC, gdarko requested changes
Hey @azaricstefan - Sorry to nag you again, looks like it still doesn't pass code style check. Can you please re-run pint? Thanks.

2024-06-05 12:48 UTC, azaricstefan commented
Sure, I will run them today again.

2024-06-06 10:28 UTC, gdarko commented
Hey @azaricstefan - Closing this in favor of pr #100 that comes after changing the namespace of the app.

2024-06-06 10:28 UTC, closed without merging